# Generated by Django 3.1.7 on 2022-01-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
