# Generated by Django 3.1.7 on 2022-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_team',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue')], max_length=20, null=True),
        ),
    ]
