# Generated by Django 4.0.1 on 2022-01-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20220109_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('MATCHING', 'Matching'), ('PLAYING', 'Playing'), ('COMPLETE', 'Complete'), ('CANCELED', 'Canceled')], max_length=20),
        ),
    ]
