# Generated by Django 3.1.7 on 2022-01-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220105_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='line',
            field=models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'Adc'), ('SUPPORT', 'Support')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
